name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: read
      deployments: write
    runs-on: macos-14


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Build Swift package
        run: |
          swift build --configuration release

      - name: Find compiled executable
        run: |
          find . -name "IgniteStarter"
        shell: bash

      - name: Run Swift package
        run: ./.build/arm64-apple-macosx/release/IgniteStarter # Adjust path if necessary

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GH_TOKEN }} # Replace with your secret name
          publish_dir: ./Build  # Adjust to your build output directory containing static files
          publish_branch: gh-pages
